web/models.py
from . import db

class User(db.Model):
    id: int = db.Column(db.Integer, primary_key=True)
    username: str = db.Column(db.String(40), index=False, unique=False)
    email: str = db.Column(db.String(80), index=True, unique=True)
    password: str = db.Column(db.String(128))

    def __repr__(self) -> str:
        return f'User: <{self.username}>\nEmail: <{self.email}>'

class Product(db.Model):
    id: int = db.Column(db.Integer, primary_key=True)
    name: str = db.Column(db.String(80), index=True, unique=False)
    description: str = db.Column(db.String(1024), index=False, unique=False)
    price: int = db.Column(db.Integer, index=False, unique=False)

    def __repr__(self) -> str:
        return f'Product: <{self.name}>\nPrice: <{self.price}>'

web/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo

class LoginForm(FlaskForm):
    username: str = StringField('Username', validators=[DataRequired()])
    password: str = PasswordField('Password', validators=[DataRequired()])
    remember_me: bool = BooleanField('Remember me')
    submit = SubmitField()

class RegisterForm(FlaskForm):
    username: str = StringField()
    email: str = StringField()
    password: str = PasswordField('Password', validators=[DataRequired()])
    password2: str = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField()

web/__init__.py
from flask import Flask
from .config import Config, DB_NAME
from flask_sqlalchemy import SQLAlchemy
import os

db: SQLAlchemy = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app) 
    
    from .views import views
    from .auth import auth

    create_db(app)

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    return app

def create_db(app: Flask):
    if not os.path.exists(f'web/{DB_NAME}'):
        with app.app_context():
            db.create_all()
            print('Database Created!')
    else:
        print('Database already created!')

web/auth.py
from flask import Blueprint, render_template, url_for
from .forms import LoginForm, RegisterForm

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form: LoginForm = LoginForm()
    return render_template('login.html', form=form)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    form: RegisterForm = RegisterForm()
    return render_template('register.html', form=form)

@auth.route('logout')
def logout():
    return 'You have been logged out'

web/views.py
from flask import Blueprint, render_template, url_for

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return 'Welcome to my e-commerce'

@views.route('/home')
def home():
    return render_template('home.html')

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="navbar-collapse ">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('views.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('auth.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                </ul>
            <div class="justify-content-end">
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
            </div>
            </div>
        </nav>
        <div>
            flashed messages
        </div>
    </header>
    <main>
        {% block content %} {% endblock %}
    </main>
    <footer>
        
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

web/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
    <h1>Welcome to the Home Page</h1>
{% endblock %}

web/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
    <h1>Welcome to the Login Page</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        
        {{ form.username.label() }}<br>
        {{ form.username(placeholder="Username") }}<br>

        {{ form.password.label() }}<br>
        {{ form.password(placeholder="Password") }}<br>

        {{ form.remember_me() }}
        {{ form.remember_me.label() }}<br>

        {{ form.submit() }}
    </form>
{% endblock %}

web/templates/register.html
{% extends "base.html" %}
{% block title %}
Register
{% endblock %}

{% block content %}
    <div class="content-fluid justify-content-center">
        <h1>Welcome to the register Page</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}

            {{ form.username.label() }}<br>
            {{ form.username(placeholder="Username")}}<br>

            {{ form.email.label() }}<br>
            {{ form.email(placeholder="Email address")}}<br>

            {{ form.password.label() }} <br>
            {{ form.password(placeholder="Password") }} <br>

            {{ form.password2.label() }} <br>
            {{ form.password2(placeholder="Confirm your password") }} <br>

            {{ form.submit() }}
        </form>
    </div>
{% endblock %}